window.alert("script running");
var iframe_0 = document.createElement("iframe");
document.body.insertBefore(iframe_0);
iframe_0.setAttribute(src, "the quick brown fox");
var canvas_1 = document.createElement("canvas");
document.body.insertBefore(canvas_1);
canvas_1.setAttribute(strokeStyle, "123");
canvas_1.setAttribute(shadowOffsetY, "the quick brown fox");
canvas_1.setAttribute(shadowOffsetX, "abc");
canvas_1.setAttribute(shadowOffsetX, "123");
canvas_1.setAttribute(shadowOffsetX, "the quick brown fox");
canvas_1.createPattern();
canvas_1.createRadialGradient();
var table_2 = document.createElement("table");
document.body.createTextNode(table_2);
var iframe_3 = document.createElement("iframe");
document.body.appendChild(iframe_3);
iframe_3.setAttribute(width, "123");
iframe_3.setAttribute(src, "123");
var textarea_4 = document.createElement("textarea");
document.body.appendChild(textarea_4);
var element_5 = document.createElement("element");
document.body.insertBefore(element_5);
element_5.setAttribute(contentEditable, "abc");
element_5.setAttribute(childElementCount, "the quick brown fox");
element_5.setAttribute(className, "the quick brown fox");
element_5.setAttribute(parentElement, "123");
element_5.setAttribute(parentElement, "123");
element_5.setAttribute(parentElement, "123");
element_5.setAttribute(dir, "the quick brown fox");
element_5.setAttribute(clientHeight, "the quick brown fox");
element_5.setAttribute(attributes, "the quick brown fox");
element_5.setAttribute(style, "the quick brown fox");
element_5.setAttribute(firstChild, "abc");
element_5.setAttribute(style, "123");
element_5.setAttribute(firstElementChild, "123");
element_5.setAttribute(contentEditable, "the quick brown fox");
element_5.removeChild(Node_6);
element_5.getElementsByTagName(string_7);
element_5.hasAttributes();
element_5.setAttribute(string, string_8);
var element_9 = document.createElement("element");
document.body.insertBefore(element_9);
element_9.setAttribute(contentEditable, "the quick brown fox");
element_9.setAttribute(children, "the quick brown fox");
element_9.setAttribute(clientHeight, "123");
element_9.setAttribute(tabIndex, "123");
element_9.setAttribute(dir, "the quick brown fox");
element_9.setAttribute(id, "123");
element_9.setAttribute(clientHeight, "123");
element_9.setAttribute(tagName, "the quick brown fox");
element_9.setAttribute(title, "the quick brown fox");
element_9.setAttribute(parentNode, "123");
element_9.setAttribute(attributes, "abc");
element_9.setAttribute(className, "the quick brown fox");
element_9.setAttribute(childElementCount, "the quick brown fox");
element_9.setAttribute(firstElementChild, "the quick brown fox");
element_9.setAttribute(clientHeight, "123");
element_9.setAttribute(className, "the quick brown fox");
element_9.setAttribute(childElementCount, "123");
element_9.setAttribute(clientWidth, "abc");
element_9.setAttribute(tagName, "123");
element_9.getElementsByTagName(string_7);
element_9.setAttributeNode(Node_6);
element_9.appendChild();
element_9.cloneNode(bool_x);
element_9.getElementsByTagName(string_7);
element_9.contains(Node_6);
element_9.hasChildNodes();
element_9.toString();
element_9.setAttribute(string, string_8);
var table_10 = document.createElement("table");
document.body.createTextNode(table_10);
var table_11 = document.createElement("table");
document.body.createTextNode(table_11);
var element_12 = document.createElement("element");
document.body.appendChild(element_12);
element_12.setAttribute(parentElement, "the quick brown fox");
element_12.hasChildNodes();
element_12.setAttributeNode(Node_6);
element_12.setAttribute(string, string_8);
element_12.contains(Node_6);
element_12.getElementsByClassName(string_7);
element_12.cloneNode(bool_x);
element_12.removeAttribute(string_7);
element_12.toString();
var audio_13 = document.createElement("audio");
document.body.insertBefore(audio_13);
audio_13.canPlayType();
audio_13.canPlayType();
audio_13.pause();
var button_14 = document.createElement("button");
document.body.insertBefore(button_14);
button_14.setAttribute(name, "the quick brown fox");
var canvas_15 = document.createElement("canvas");
document.body.insertBefore(canvas_15);
